import type { InvisibleWeatherPreset } from './types';

export const INVISIBLE_WEATHER_PRESETS = [
	{
		id: 'monsoon-ledger',
		name: 'Monsoon Ledger',
		description: 'Asymmetrical cream and storm-green prints joined by a narrow mid-field river.',
		state: {
			layout: 'salon-wall',
			artworkCount: 9,
			paletteId: 'monsoon-ledger',
			noiseMode: 'gradient',
			depth: 3,
			frequency: 1.7,
			warpStrength: 0.34,
			angleMode: 'free',
			thresholdMode: 'river',
			thresholdWidth: 0.09,
			motion: 'migrate',
			pathDensity: 1,
			pathLength: 42,
			multiplier: 1,
			turns: 1.25,
			strokeWidth: 1,
			dualInk: true,
			grain: 0.18,
			shadow: 0.52,
			frameFamily: 'quiet-wood',
			orientation: 'auto',
			speed: 0.55
		}
	},
	{
		id: 'orthogonal-arguments',
		name: 'Orthogonal Arguments',
		description: 'Orthogonal rust-and-ink currents arranged like a cabinet of city fragments.',
		state: {
			layout: 'cabinet',
			artworkCount: 8,
			paletteId: 'tramline-rust',
			depth: 2,
			frequency: 2.1,
			warpStrength: 0.22,
			angleMode: 'orthogonal',
			thresholdMode: 'delta',
			thresholdWidth: 0.07,
			motion: 'still',
			pathDensity: 1.12,
			pathLength: 34,
			multiplier: 1.2,
			turns: 1,
			strokeWidth: 0.9,
			dualInk: true,
			grain: 0.24,
			shadow: 0.62,
			frameFamily: 'oxidised-brass',
			orientation: 'auto',
			speed: 0.75
		}
	},
	{
		id: 'river-between-walls',
		name: 'River Between Walls',
		description: 'Long contour-like channels counted across a restrained sequence of pale plates.',
		state: {
			layout: 'procession',
			artworkCount: 7,
			paletteId: 'silt-map',
			depth: 4,
			frequency: 1.25,
			warpStrength: 0.48,
			angleMode: 'soft',
			softness: 0.58,
			thresholdMode: 'river',
			thresholdWidth: 0.055,
			motion: 'migrate',
			pathDensity: 0.86,
			pathLength: 58,
			multiplier: 0.9,
			turns: 1.8,
			strokeWidth: 0.82,
			dualInk: true,
			grain: 0.12,
			shadow: 0.4,
			frameFamily: 'limewash',
			orientation: 'landscape',
			speed: 0.7
		}
	},
	{
		id: 'nine-quiet-rooms',
		name: 'Nine Quiet Rooms',
		description: 'A measured grid of low-warp fields with room for every line to breathe.',
		state: {
			layout: 'quiet-grid',
			artworkCount: 9,
			paletteId: 'storm-glass',
			depth: 2,
			frequency: 1.45,
			warpStrength: 0.08,
			angleMode: 'free',
			thresholdMode: 'river',
			thresholdWidth: 0.055,
			motion: 'breathe',
			pathDensity: 0.72,
			pathLength: 48,
			multiplier: 0.8,
			turns: 0.8,
			strokeWidth: 0.72,
			dualInk: true,
			grain: 0.08,
			shadow: 0.34,
			frameFamily: 'white-oak',
			orientation: 'auto',
			speed: 0.55
		}
	},
	{
		id: 'salon-after-closing',
		name: 'Salon After Closing',
		description: 'A dark asymmetrical room gathered around one large, gently lit anchor work.',
		state: {
			layout: 'salon-wall',
			artworkCount: 10,
			paletteId: 'night-museum',
			depth: 3,
			frequency: 2.35,
			warpStrength: 0.4,
			angleMode: 'soft',
			thresholdMode: 'islands',
			thresholdWidth: 0.1,
			motion: 'breathe',
			pathDensity: 0.92,
			pathLength: 44,
			multiplier: 1.35,
			turns: 1.55,
			strokeWidth: 0.78,
			dualInk: true,
			grain: 0.2,
			shadow: 0.72,
			frameFamily: 'black-lacquer',
			orientation: 'auto',
			speed: 0.55
		}
	},
	{
		id: 'cabinet-of-crosswinds',
		name: 'Cabinet of Crosswinds',
		description: 'Nested channels and tail-islands filed into small archival compartments.',
		state: {
			layout: 'cabinet',
			artworkCount: 12,
			paletteId: 'jute-and-ink',
			depth: 4,
			frequency: 1.9,
			warpStrength: 0.55,
			angleMode: 'alternating',
			thresholdMode: 'delta',
			thresholdWidth: 0.075,
			motion: 'still',
			pathDensity: 1.06,
			pathLength: 38,
			multiplier: 1.1,
			turns: 1.4,
			strokeWidth: 0.84,
			dualInk: true,
			grain: 0.3,
			shadow: 0.5,
			frameFamily: 'dark-jute',
			orientation: 'portrait',
			speed: 0.65
		}
	},
	{
		id: 'three-large-silences',
		name: 'Three Large Silences',
		description: 'Three luminous field specimens suspended in a nearly black room.',
		state: {
			layout: 'triptych',
			artworkCount: 3,
			paletteId: 'night-museum',
			depth: 3,
			frequency: 1.6,
			warpStrength: 0.3,
			angleMode: 'free',
			thresholdMode: 'off',
			thresholdWidth: 0.08,
			motion: 'breathe',
			pathDensity: 0.52,
			pathLength: 68,
			multiplier: 1,
			turns: 1.2,
			strokeWidth: 0.92,
			dualInk: false,
			grain: 0.1,
			shadow: 0.78,
			frameFamily: 'black-lacquer',
			orientation: 'landscape',
			speed: 0.8
		}
	}
] as const satisfies readonly InvisibleWeatherPreset[];

export const PRESETS = INVISIBLE_WEATHER_PRESETS;

export function getPreset(id: string): InvisibleWeatherPreset {
	return PRESETS.find((preset) => preset.id === id) ?? PRESETS[0];
}
