<script lang="ts">
	import type { FractalFamily } from '$lib/visualizations/fractal-atlas/types';

	type Branch = {
		label: string;
		description: string;
		families: { id: FractalFamily; label: string }[];
	};

	const branches: Branch[] = [
		{
			label: 'Escape-time maps',
			description: 'A pixel launches an orbit and the renderer asks whether it escapes.',
			families: [
				{ id: 'mandelbrot', label: 'Mandelbrot' },
				{ id: 'julia', label: 'Julia' },
				{ id: 'multibrot', label: 'Multibrot' },
				{ id: 'burning-ship', label: 'Burning Ship' },
				{ id: 'tricorn', label: 'Tricorn' },
				{ id: 'phoenix', label: 'Phoenix' }
			]
		},
		{
			label: 'Convergence basins',
			description: 'A pixel votes for the root reached by an answer-finding process.',
			families: [{ id: 'newton', label: 'Newton fractals' }]
		},
		{
			label: 'Orbit density',
			description:
				'Escaping routes accumulate into a histogram instead of one colour per parameter.',
			families: [{ id: 'buddhabrot', label: 'Buddhabrot' }]
		},
		{
			label: 'Recursive cousins',
			description: 'Affine choices, removal rules, and grammars construct limiting objects.',
			families: [
				{ id: 'barnsley-fern', label: 'Barnsley fern' },
				{ id: 'sierpinski', label: 'Sierpiński' },
				{ id: 'l-system', label: 'L-systems' }
			]
		}
	];

	function choose(family: FractalFamily) {
		window.dispatchEvent(
			new CustomEvent('fractal-atlas-command', { detail: { family, source: 'family-tree' } })
		);
	}
</script>

<figure class="family-tree article-breakout not-prose" aria-labelledby="family-tree-heading">
	<div class="tree-heading">
		<p>Field classification</p>
		<h2 id="family-tree-heading">Several questions, one atlas</h2>
	</div>
	<div class="branches">
		{#each branches as branch (branch.label)}
			<section>
				<div class="branch-rule" aria-hidden="true"></div>
				<h3>{branch.label}</h3>
				<p>{branch.description}</p>
				<div class="family-links">
					{#each branch.families as family (family.id)}
						<button type="button" onclick={() => choose(family.id)}>
							{family.label}
							<span aria-hidden="true">→</span>
						</button>
					{/each}
				</div>
			</section>
		{/each}
	</div>
	<figcaption>
		The branches classify what the pixels and algorithms mean; they do not claim that every member
		is generated by the same recurrence.
	</figcaption>
</figure>

<style>
	.family-tree {
		position: relative;
		left: calc(50% + var(--article-breakout-offset, 0rem));
		width: min(74rem, calc(100vw - 2rem));
		margin: 2rem 0;
		transform: translateX(-50%);
		border: 1px solid var(--rule);
		border-radius: 0.7rem;
		background: var(--paper-raised);
		padding: clamp(1rem, 3vw, 1.6rem);
		box-shadow: 0 14px 38px rgb(20 16 30 / 8%);
	}

	.tree-heading p {
		margin: 0 0 0.35rem;
		color: var(--essay-ink);
		font: 700 0.7rem/1.2 var(--font-sans);
		letter-spacing: 0.16em;
		text-transform: uppercase;
	}

	.tree-heading h2 {
		margin: 0;
		font: 750 clamp(1.3rem, 2.4vw, 1.9rem) / 1.15 var(--font-sans);
	}

	.branches {
		display: grid;
		grid-template-columns: repeat(4, minmax(0, 1fr));
		gap: 1rem;
		margin-top: 1.25rem;
	}

	.branches section {
		position: relative;
		border-top: 2px solid color-mix(in oklab, var(--essay-ink) 55%, var(--rule));
		padding-top: 0.85rem;
	}

	.branches h3 {
		margin: 0;
		font: 700 0.95rem/1.25 var(--font-sans);
	}

	.branches p {
		min-height: 4.2em;
		margin: 0.45rem 0 0.8rem;
		color: var(--ink-muted);
		font: 0.78rem/1.4 var(--font-sans);
	}

	.family-links {
		display: grid;
		gap: 0.35rem;
	}

	.family-links button {
		display: flex;
		min-height: 2.75rem;
		align-items: center;
		justify-content: space-between;
		border: 1px solid var(--rule);
		border-radius: 0.35rem;
		background: var(--paper);
		padding: 0.45rem 0.65rem;
		color: var(--ink);
		font: 650 0.75rem/1.2 var(--font-sans);
		text-align: left;
		cursor: pointer;
	}

	.family-links button:hover {
		border-color: var(--essay-ink);
	}

	figcaption {
		margin-top: 1rem;
		color: var(--ink-muted);
		font: 0.78rem/1.45 var(--font-sans);
	}

	@media (max-width: 64rem) {
		.branches {
			grid-template-columns: repeat(2, minmax(0, 1fr));
		}
	}

	@media (max-width: 38rem) {
		.branches {
			grid-template-columns: 1fr;
		}

		.branches p {
			min-height: auto;
		}
	}

	@media (forced-colors: active) {
		.family-tree,
		.family-links button {
			border: 2px solid CanvasText;
		}
	}
</style>
