import type { EvidenceKind, RhythmDatum } from './types';

export const EVIDENCE_KIND_LABELS: Record<EvidenceKind, string> = {
	'authoritative-range': 'Authoritative range',
	'measured-summary': 'Measured summary',
	'derived-conversion': 'Derived conversion',
	'model-derived': 'Model-derived illustration'
};

export const RHYTHM_EVIDENCE: readonly RhythmDatum[] = [
	{
		id: 'heartbeat',
		label: 'Heartbeat',
		unit: 'beats/min and seconds/beat',
		period: '72 beats/min; 0.833 seconds/beat',
		kind: 'derived-conversion',
		supportKinds: ['derived-conversion', 'authoritative-range'],
		sourceLabel: 'NHLBI — How the Heart Beats',
		sourceUrl: 'https://www.nhlbi.nih.gov/health/heart/heart-beats',
		additionalSources: [
			{
				label: 'Donald & Lakatta (2023) — coupled cardiac pacemaker clocks',
				url: 'https://doi.org/10.1098/rstb.2022.0180'
			}
		],
		population: 'Adults at rest',
		conditions: 'Illustrative 72 beats/min within the separately stated 60–100 beats/min range.',
		limitations: [
			'The trace is an illustrative pulse rhythm, not a diagnostic ECG.',
			'Cardiac pacemaking couples membrane-voltage and intracellular calcium-clock mechanisms.'
		]
	},
	{
		id: 'breathing',
		label: 'Breathing',
		unit: 'breaths/min and seconds/cycle',
		period: '15 breaths/min; 4 seconds/cycle',
		kind: 'derived-conversion',
		supportKinds: ['derived-conversion', 'authoritative-range'],
		sourceLabel: 'MedlinePlus — Normal adult breathing rate',
		sourceUrl: 'https://medlineplus.gov/ency/article/007198.htm',
		additionalSources: [
			{
				label: 'Fogarty et al. (2018) — respiratory rhythm generation and modulation',
				url: 'https://doi.org/10.1152/physiol.00002.2018'
			}
		],
		population: 'Healthy adults at rest',
		conditions: 'Illustrative 15 breaths/min within the separately stated 12–20 breaths/min range.',
		limitations: [
			'Breathing is generated by central neural patterning and modulated by chemoreflex feedback.',
			'Rate varies with posture, activity, illness, medication and measurement conditions.'
		]
	},
	{
		id: 'mayer-wave',
		label: 'Mayer pressure wave',
		unit: 'normalized amplitude',
		period: 'about 0.1 Hz; about 10 seconds',
		kind: 'measured-summary',
		sourceLabel: 'Julien (2006), Cardiovascular Research',
		sourceUrl: 'https://doi.org/10.1016/j.cardiores.2005.11.008',
		doi: '10.1016/j.cardiores.2005.11.008',
		conditions: 'A normalized sinusoid represents the approximate frequency only.',
		limitations: [
			'Amplitude is deliberately normalized because magnitude and mechanism vary.',
			'A smooth teaching curve is not a blood-pressure recording.'
		]
	},
	{
		id: 'glucose-insulin',
		label: 'Fast glucose–insulin oscillation',
		unit: 'within-signal normalized level',
		period: 'illustrative 13-minute cycle; glucose leads insulin by about 2 minutes',
		kind: 'measured-summary',
		sourceLabel: 'Lang et al. (1979), New England Journal of Medicine',
		sourceUrl: 'https://doi.org/10.1056/NEJM197911083011903',
		doi: '10.1056/NEJM197911083011903',
		population: 'Ten healthy participants sampled every minute for one to two hours',
		conditions: 'Regular basal cycles were reported in five of ten participants.',
		limitations: [
			'The smooth paired curves are stylized, not raw participant measurements.',
			'Values are normalized within each signal and must not be read as concentrations.'
		]
	},
	{
		id: 'cortisol-ultradian',
		label: 'Cortisol ultradian activity',
		unit: 'normalized modeled level',
		period: 'about 60–90 minutes; 90 minutes illustrated',
		kind: 'measured-summary',
		sourceLabel: 'Oster et al. (2017), Endocrine Reviews',
		sourceUrl: 'https://doi.org/10.1210/er.2015-1080',
		doi: '10.1210/er.2015-1080',
		conditions: 'A 90-minute ripple is used at the upper end of a reviewed 60–90-minute band.',
		limitations: [
			'The ripple is model-derived, not a row of measured samples.',
			'Pulse timing and magnitude vary between people and across the day.'
		]
	},
	{
		id: 'lh-gnrh',
		label: 'LH pulse timing as a GnRH surrogate',
		unit: 'pulse interval',
		period: 'commonly 1–2 hours in early follicular phase; roughly 4 hours in luteal phase',
		kind: 'authoritative-range',
		sourceLabel: 'Endotext — The Normal Menstrual Cycle and the Control of Ovulation',
		sourceUrl: 'https://www.ncbi.nlm.nih.gov/books/NBK279070/',
		population: 'Menstruating humans; timing depends on cycle phase',
		conditions: 'LH is generally measured as a surrogate for hypothalamic GnRH pulses.',
		limitations: [
			'Cycle phase, age and sex matter.',
			'Estradiol feedback becomes positive near ovulation, so the ovarian cycle is not purely negative feedback.'
		]
	},
	{
		id: 'core-temperature',
		label: 'Core temperature',
		unit: '°C',
		period: '24 hours; about 1.1 °C peak-to-trough excursion illustrated',
		kind: 'measured-summary',
		sourceLabel: 'Baehr et al. (2000), Journal of Sleep Research',
		sourceUrl: 'https://doi.org/10.1046/j.1365-2869.2000.00196.x',
		doi: '10.1046/j.1365-2869.2000.00196.x',
		population: 'Young men grouped by chronotype',
		conditions:
			'The study reported about 1.1–1.3 °C peak-to-trough depending on chronotype; nadir near 05:00.',
		limitations: [
			'This is a representative curve, not a universal human constant.',
			'“Amplitude” can mean half the peak-to-trough range; this article uses the unambiguous full excursion.'
		]
	},
	{
		id: 'daily-pressure',
		label: 'Daily blood pressure',
		unit: '% of daytime level',
		period: '24 hours; sleep region illustrated at 85%',
		kind: 'measured-summary',
		sourceLabel: 'Huart et al. (2023), Hypertension review',
		sourceUrl: 'https://doi.org/10.1161/HYPERTENSIONAHA.122.19996',
		doi: '10.1161/HYPERTENSIONAHA.122.19996',
		conditions:
			'Daytime is normalized to 100%; sleep is drawn inside the common 10–20% dipping range.',
		limitations: [
			'Not everyone exhibits normal nocturnal dipping.',
			'The display intentionally does not invent systolic or diastolic mmHg values.'
		]
	},
	{
		id: 'daily-cortisol',
		label: 'Daily salivary cortisol',
		unit: 'nmol/L',
		period: 'four summary moments across one day',
		kind: 'model-derived',
		sourceLabel: 'Dmitrieva et al. (2013), Psychoneuroendocrinology',
		sourceUrl: 'https://doi.org/10.1016/j.psyneuen.2013.05.003',
		doi: '10.1016/j.psyneuen.2013.05.003',
		population: 'Growth-mixture model of 2,894 valid days from 1,101 adults',
		conditions:
			'Model-estimated normative-profile points: waking 13.4; +30 minutes 20.4; pre-lunch 6.0; bedtime 1.5 nmol/L.',
		limitations: [
			'Four modeled class-profile points cannot resolve ultradian pulses.',
			'These salivary values are not serum reference values or individual trajectories.',
			'The study used event-relative collection moments, so their clock positions in the explorer are illustrative.'
		]
	}
] as const;

export function evidenceFor(id: string): RhythmDatum {
	const datum = RHYTHM_EVIDENCE.find((candidate) => candidate.id === id);
	if (!datum) throw new Error(`Unknown rhythm evidence id: ${id}`);
	return datum;
}

export function hasValidEvidenceClassification(value: string): value is EvidenceKind {
	return value in EVIDENCE_KIND_LABELS;
}
